// NOTE: This static data is no longer used. 
// Students data is now fetched from the API in real-time.
// The students page now uses the useStudents() hook to fetch data from the backend API
// at /api/students endpoint with proper authentication and permission handling.

// The new structure uses university_id as the primary identifier (8-digit number)
export const studentsData: any[] = [
    {
        id: "3",
        studentId: 125,
        studentName: "Michael Brown",
        campus: "Beirut",
        school: "Business",
        major: "MBA",
        semester: "Semester 2",
        year: "2025-2026",
    },
    {
        id: "4",
        studentId: 126,
        studentName: "Emily Davis",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "5",
        studentId: 127,
        studentName: "David Wilson",
        campus: "Tripoli",
        school: "Medicine",
        major: "MD",
        semester: "Semester 8",
        year: "2023-2024",
    },
    {
        id: "6",
        studentId: 128,
        studentName: "Lisa Anderson",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "7",
        studentId: 129,
        studentName: "James Taylor",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 3",
        year: "2025-2026",
    },
    {
        id: "8",
        studentId: 130,
        studentName: "Maria Garcia",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "9",
        studentId: 131,
        studentName: "Robert Martinez",
        campus: "Sidon",
        school: "Law",
        major: "LLB",
        semester: "Semester 5",
        year: "2024-2025",
    },
    {
        id: "10",
        studentId: 132,
        studentName: "Jennifer Lee",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "11",
        studentId: 133,
        studentName: "Christopher White",
        campus: "Beirut",
        school: "Engineer",
        major: "CS",
        semester: "Semester 7",
        year: "2023-2024",
    },
    {
        id: "12",
        studentId: 134,
        studentName: "Amanda Thompson",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "13",
        studentId: 135,
        studentName: "Daniel Harris",
        campus: "Tripoli",
        school: "Business",
        major: "BBA",
        semester: "Semester 6",
        year: "2024-2025",
    },
    {
        id: "14",
        studentId: 136,
        studentName: "Michelle Clark",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "15",
        studentId: 137,
        studentName: "Kevin Rodriguez",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 10",
        year: "2022-2023",
    },
    {
        id: "16",
        studentId: 138,
        studentName: "Nicole Lewis",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "17",
        studentId: 139,
        studentName: "Ryan Walker",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 1",
        year: "2025-2026",
    },
    {
        id: "18",
        studentId: 140,
        studentName: "Stephanie Hall",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "19",
        studentId: 141,
        studentName: "Brandon Allen",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 3",
        year: "2025-2026",
    },
    {
        id: "20",
        studentId: 142,
        studentName: "Rachel Young",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "21",
        studentId: 143,
        studentName: "Justin King",
        campus: "Beirut",
        school: "Business",
        major: "MBA",
        semester: "Semester 4",
        year: "2024-2025",
    },
    {
        id: "22",
        studentId: 144,
        studentName: "Megan Wright",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "23",
        studentId: 145,
        studentName: "Tyler Lopez",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 6",
        year: "2024-2025",
    },
    {
        id: "24",
        studentId: 146,
        studentName: "Ashley Hill",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "25",
        studentId: 147,
        studentName: "Jordan Scott",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 5",
        year: "2024-2025",
    },
    {
        id: "26",
        studentId: 148,
        studentName: "Brittany Green",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "27",
        studentId: 149,
        studentName: "Austin Adams",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 7",
        year: "2023-2024",
    },
    {
        id: "28",
        studentId: 150,
        studentName: "Samantha Baker",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "29",
        studentId: 151,
        studentName: "Nathan Gonzalez",
        campus: "Beirut",
        school: "Business",
        major: "BBA",
        semester: "Semester 2",
        year: "2025-2026",
    },
    {
        id: "30",
        studentId: 152,
        studentName: "Kayla Nelson",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "31",
        studentId: 153,
        studentName: "Zachary Carter",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "32",
        studentId: 154,
        studentName: "Hannah Mitchell",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "33",
        studentId: 155,
        studentName: "Caleb Perez",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 7",
        year: "2023-2024",
    },
    {
        id: "34",
        studentId: 156,
        studentName: "Alexis Roberts",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "35",
        studentId: 157,
        studentName: "Ian Turner",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 1",
        year: "2025-2026",
    },
    {
        id: "36",
        studentId: 158,
        studentName: "Victoria Phillips",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "37",
        studentId: 159,
        studentName: "Gabriel Campbell",
        campus: "Beirut",
        school: "Business",
        major: "MBA",
        semester: "Semester 6",
        year: "2024-2025",
    },
    {
        id: "38",
        studentId: 160,
        studentName: "Jasmine Parker",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "39",
        studentId: 161,
        studentName: "Lucas Evans",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 8",
        year: "2023-2024",
    },
    {
        id: "40",
        studentId: 162,
        studentName: "Destiny Edwards",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "41",
        studentId: 163,
        studentName: "Mason Collins",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 3",
        year: "2025-2026",
    },
    {
        id: "42",
        studentId: 164,
        studentName: "Paige Stewart",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "43",
        studentId: 165,
        studentName: "Ethan Sanchez",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 5",
        year: "2024-2025",
    },
    {
        id: "44",
        studentId: 166,
        studentName: "Jenna Morris",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "45",
        studentId: 167,
        studentName: "Owen Rogers",
        campus: "Beirut",
        school: "Business",
        major: "BBA",
        semester: "Semester 8",
        year: "2023-2024",
    },
    {
        id: "46",
        studentId: 168,
        studentName: "Chloe Reed",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "47",
        studentId: 169,
        studentName: "Hunter Cook",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 2",
        year: "2025-2026",
    },
    {
        id: "48",
        studentId: 170,
        studentName: "Abigail Morgan",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "49",
        studentId: 171,
        studentName: "Connor Bailey",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 6",
        year: "2024-2025",
    },
    {
        id: "50",
        studentId: 172,
        studentName: "Haley Rivera",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "51",
        studentId: 173,
        studentName: "Blake Cooper",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 9",
        year: "2022-2023",
    },
    {
        id: "52",
        studentId: 174,
        studentName: "Kimberly Richardson",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "53",
        studentId: 175,
        studentName: "Wyatt Cox",
        campus: "Beirut",
        school: "Business",
        major: "MBA",
        semester: "Semester 1",
        year: "2025-2026",
    },
    {
        id: "54",
        studentId: 176,
        studentName: "Brooke Howard",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "55",
        studentId: 177,
        studentName: "Cole Ward",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 7",
        year: "2023-2024",
    },
    {
        id: "56",
        studentId: 178,
        studentName: "Mackenzie Torres",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "57",
        studentId: 179,
        studentName: "Landon Peterson",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "58",
        studentId: 180,
        studentName: "Sydney Gray",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "59",
        studentId: 181,
        studentName: "Tristan Ramirez",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 2",
        year: "2025-2026",
    },
    {
        id: "60",
        studentId: 182,
        studentName: "Mariah James",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "61",
        studentId: 183,
        studentName: "Devin Watson",
        campus: "Beirut",
        school: "Business",
        major: "BBA",
        semester: "Semester 5",
        year: "2024-2025",
    },
    {
        id: "62",
        studentId: 184,
        studentName: "Tiffany Brooks",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "63",
        studentId: 185,
        studentName: "Garrett Kelly",
        campus: "Sidon",
        school: "Medicine",
        major: "MD",
        semester: "Semester 3",
        year: "2025-2026",
    },
    {
        id: "64",
        studentId: 186,
        studentName: "Courtney Sanders",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "65",
        studentId: 187,
        studentName: "Jared Price",
        campus: "Beirut",
        school: "Arts",
        major: "BA",
        semester: "Semester 8",
        year: "2023-2024",
    },
    {
        id: "66",
        studentId: 188,
        studentName: "Danielle Bennett",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
    {
        id: "67",
        studentId: 189,
        studentName: "Trevor Wood",
        campus: "Tripoli",
        school: "Law",
        major: "LLB",
        semester: "Semester 6",
        year: "2024-2025",
    },
    {
        id: "68",
        studentId: 190,
        studentName: "Crystal Barnes",
        campus: "Zahle",
        school: "Engineer",
        major: "ENG",
        semester: "Semester 4",
        year: "2025-2026",
    },
];
